name: location_example
description: Demonstrates how to use the location plugin.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_blue: ^0.8.0
  location: ^4.3.0
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true